# Generated by Django 4.1.3 on 2022-11-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='spicy_level',
            field=models.IntegerField(),
        ),
    ]
