# Generated by Django 4.1.3 on 2022-11-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuApp', '0002_alter_menuitem_spicy_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='cuisine_id',
            new_name='cuisine',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='spicy_level',
            field=models.IntegerField(null=True),
        ),
    ]
